PROJECT_FOLDER ?= .

.PHONY: help \
        test test-scenarios test-basic \
        test-cacerts test-cacerts-scenarios test-cacerts-basic \
        test-jumpstarter-cli test-jumpstarter-cli-scenarios test-jumpstarter-cli-basic \
        test-nrf-tools test-nrf-tools-scenarios test-nrf-tools-basic \
        test-postgresql test-postgresql-scenarios test-postgresql-basic \
        test-pre-commit test-pre-commit-scenarios test-pre-commit-basic \
        test-uv test-uv-scenarios test-uv-basic \
        check lint \
        cleanup-runs cleanup-runs-auto cleanup-runs-failed cleanup-runs-failed-auto

# Default target
help: ## Diese Hilfe anzeigen
	@echo "Verfügbare Targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-40s\033[0m %s\n", $$1, $$2}'

# ── Alle Features ──────────────────────────────────────────────────────────────

test: ## Alle Feature-Tests ausführen (Basis + Scenarios)
	devcontainer features test -p $(PROJECT_FOLDER)

test-scenarios: ## Nur Scenario-Tests aller Features ausführen
	devcontainer features test -p $(PROJECT_FOLDER) --skip-autogenerated

test-basic: ## Nur Basis-Tests (test.sh) aller Features ausführen
	devcontainer features test -p $(PROJECT_FOLDER) --skip-scenarios

# ── Feature: cacerts ───────────────────────────────────────────────────────────

test-cacerts: ## Tests für Feature 'cacerts' ausführen
	devcontainer features test -p $(PROJECT_FOLDER) -f cacerts

test-cacerts-scenarios: ## Nur Scenario-Tests für Feature 'cacerts'
	devcontainer features test -p $(PROJECT_FOLDER) -f cacerts --skip-autogenerated

test-cacerts-basic: ## Nur Basis-Test (test.sh) für Feature 'cacerts'
	devcontainer features test -p $(PROJECT_FOLDER) -f cacerts --skip-scenarios

# ── Feature: jumpstarter-cli ───────────────────────────────────────────────────

test-jumpstarter-cli: ## Tests für Feature 'jumpstarter-cli' ausführen
	devcontainer features test -p $(PROJECT_FOLDER) -f jumpstarter-cli

test-jumpstarter-cli-scenarios: ## Nur Scenario-Tests für Feature 'jumpstarter-cli'
	devcontainer features test -p $(PROJECT_FOLDER) -f jumpstarter-cli --skip-autogenerated

test-jumpstarter-cli-basic: ## Nur Basis-Test (test.sh) für Feature 'jumpstarter-cli'
	devcontainer features test -p $(PROJECT_FOLDER) -f jumpstarter-cli --skip-scenarios

# ── Feature: nrf-tools ────────────────────────────────────────────────────────

test-nrf-tools: ## Tests für Feature 'nrf-tools' ausführen (kein autogenerierter Test)
	devcontainer features test -p $(PROJECT_FOLDER) -f nrf-tools --skip-autogenerated

test-nrf-tools-scenarios: ## Nur Scenario-Tests für Feature 'nrf-tools'
	devcontainer features test -p $(PROJECT_FOLDER) -f nrf-tools --skip-autogenerated

test-nrf-tools-basic: ## Nur Basis-Test (test.sh) für Feature 'nrf-tools'
	devcontainer features test -p $(PROJECT_FOLDER) -f nrf-tools --skip-autogenerated --skip-scenarios

# ── Feature: postgresql ────────────────────────────────────────────────────────

test-postgresql: ## Tests für Feature 'postgresql' ausführen
	devcontainer features test -p $(PROJECT_FOLDER) -f postgresql

test-postgresql-scenarios: ## Nur Scenario-Tests für Feature 'postgresql'
	devcontainer features test -p $(PROJECT_FOLDER) -f postgresql --skip-autogenerated

test-postgresql-basic: ## Nur Basis-Test (test.sh) für Feature 'postgresql'
	devcontainer features test -p $(PROJECT_FOLDER) -f postgresql --skip-scenarios

# ── Feature: pre-commit ────────────────────────────────────────────────────────

test-pre-commit: ## Tests für Feature 'pre-commit' ausführen
	devcontainer features test -p $(PROJECT_FOLDER) -f pre-commit

test-pre-commit-scenarios: ## Nur Scenario-Tests für Feature 'pre-commit'
	devcontainer features test -p $(PROJECT_FOLDER) -f pre-commit --skip-autogenerated

test-pre-commit-basic: ## Nur Basis-Test (test.sh) für Feature 'pre-commit'
	devcontainer features test -p $(PROJECT_FOLDER) -f pre-commit --skip-scenarios

# ── Feature: uv ───────────────────────────────────────────────────────────────

test-uv: ## Tests für Feature 'uv' ausführen
	devcontainer features test -p $(PROJECT_FOLDER) -f uv

test-uv-scenarios: ## Nur Scenario-Tests für Feature 'uv'
	devcontainer features test -p $(PROJECT_FOLDER) -f uv --skip-autogenerated

test-uv-basic: ## Nur Basis-Test (test.sh) für Feature 'uv'
	devcontainer features test -p $(PROJECT_FOLDER) -f uv --skip-scenarios

# ── Qualitätssicherung ─────────────────────────────────────────────────────────

check: ## README-Versionsreferenzen aller Features prüfen
	bash scripts/check-feature-readme-versions.sh

lint: check ## Alias für check

# ── GitHub Actions Wartung ─────────────────────────────────────────────────────

cleanup-runs: ## Alte GitHub Actions Runs löschen (behält die 20 neuesten)
	bash scripts/cleanup-runs.sh

cleanup-runs-auto: ## Alte Runs löschen ohne Bestätigungsabfrage (behält 20)
	bash scripts/cleanup-runs.sh -y

cleanup-runs-failed: ## Alle fehlgeschlagenen Runs löschen (mit Bestätigung)
	bash scripts/cleanup-runs.sh --failed

cleanup-runs-failed-auto: ## Alle fehlgeschlagenen Runs ohne Rückfrage löschen
	bash scripts/cleanup-runs.sh -y --failed
