name: "Security Scan"
on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./src"
        continue-on-error: true

      - name: Run ShellCheck with SARIF output
        run: |
          # Create directory if it doesn't exist
          mkdir -p $(dirname shellcheck-results.sarif)

          # Run shellcheck and create SARIF output
          if find ./src -name "*.sh" -type f | head -1 | read; then
            find ./src -name "*.sh" -type f -exec shellcheck -f sarif {} + > shellcheck-results.sarif 2>/dev/null || {
              echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"shellcheck"}},"results":[]}]}' > shellcheck-results.sarif
            }
          else
            echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"shellcheck"}},"results":[]}]}' > shellcheck-results.sarif
          fi

      - name: Upload ShellCheck results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('shellcheck-results.sarif') != ''
        with:
          sarif_file: shellcheck-results.sarif
